apiVersion: skaffold/v2beta12
kind: Config
metadata:
  name: hugo-blog-skaffold
build:
  tagPolicy:
    customTemplate:
      template: "{{.TIME}}_{{.HASH}}"
      components:
        - name: TIME
          dateTime:
            format: "2006-01-02"
            timezone: "UTC"
        - name: HASH
          gitCommit:
            variant: AbbrevCommitSha
  artifacts:
    - image: image/hugo-blog
      docker:
        dockerfile: Dockerfile
deploy:
  kustomize:
    paths:
      - k8s/base
profiles:
  - name: development
    deploy:
      kustomize:
        paths:
          - k8s/overlay/development
  - name: production
    deploy:
      kustomize:
        paths:
          - k8s/overlay/production
