baseurl = "localhost"
languageCode = "en-us"
theme = "hello-friend-ng"
title = "My Blog"

PygmentsCodeFences = true
PygmentsStyle = "monokai"

copyright = "This work is licensed under a Creative Commons Attribution-NonCommercial 4.0 International License." # This message is only used by the RSS template.
paginate = 10
rssLimit = 10

# googleAnalytics = ""
# disqusShortname = ""

archetypeDir = "archetypes"
contentDir   = "content"
dataDir      = "data"
layoutDir    = "layouts"
publishDir   = "public"

buildDrafts  = false
buildFuture  = false
buildExpired = false
canonifyURLs = true

enableRobotsTXT = true
enableGitInfo   = false
enableEmoji     = true
enableMissingTranslationPlaceholders = false
disableRSS     = false
disableSitemap = false
disable404     = false
disableHugoGeneratorInject = false

[permalinks]
  posts = "/posts/:year/:month/:title/"

[author]
  name = "Justin Hung"

[blackfriday]
  hrefTargetBlank = true

[params]
dateform = "Jan 2, 2006"
dateformNum = "2006-01-02"
dateformNumTime = "2006-01-02 15:04"
dateformShort = "Jan 2"

# Subtitle for home
homeSubtitle = "Software Engineer"

# Set disableReadOtherPosts to true in order to hide the links to other posts.
disableReadOtherPosts = false

# Enable sharing buttons, if you linke
enableSharingButtons = true

# Metadata mostly used in document's head
description = "My new homepage or blog"
images = [""]
keywords = "homepage, blog"

# Default theme "light" or "dark"
defaultTheme = "dark"

# Social icons
[[params.social]]
name = "twitter"
url = "https://twitter.com/"

[[params.social]]
name = "email"
url = "mailto:nobody@example.com"

[[params.social]]
name = "github"
url = "https://github.com/"

[[params.social]]
name = "linkedin"
url = "https://www.linkedin.com/"

[[params.social]]
name = "stackoverflow"
url = "https://www.stackoverflow.com/"

[taxonomies]
category = "blog"
series = "series"
tag = "tags"

[languages]
[languages.en]
copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'
keywords = ""
readOtherPosts = "Read other posts"
subtitle = "Blog"
title = "Justin Hung"

[languages.en.params.logo]
logoHomeLink = "/"
logoText = "cd ~"
# or
#
# path = "/img/your-example-logo.svg"
# alt = "Your example logo alt text"

# And you can even create generic menu
[[menu.main]]
identifier = "blog"
name = "Blog"
url = "/posts"
