apiVersion: v1
kind: ConfigMap
metadata:
  name: springk8s-profile-cm
  namespace: springk8s
data:
  DEPLOYMENT_ENV: dev
  application-dev.yaml: |
    server:
      port: 8085
      shutdown: "graceful"
    spring:
      application:
        name: springk8s-dev-config
      profiles:
        active: dev
      lifecycle:
        timeout-per-shutdown-phase: "20s"
    management:
      endpoints:
        web:
          exposure:
            include: "*"
      endpoint:
        health:
          show-details: always
          probes:
            enabled: true
      metrics:
        tags:
          application: ${info.app.name}
    info:
      app:
        name: SpringK8s-dev
        description: Spring Boot actuator for k8s cloud stack demo
        version: 1.0.0
        encoding: UTF-8
        java.version: 1.8