apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
patchesStrategicMerge:
  - patch.yaml
configMapGenerator:
  - files:
      - application-prod.yaml
    name: springk8s-profile-cm