apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: blog
  name: blog-deploy
  namespace: blog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blog
  template:
    metadata:
      labels:
        app: blog
        version: v1
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: blog
          image: hugo-app
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: "256Mi"
              cpu: "300m"
            limits:
              memory: "512Mi"
              cpu: "500m"
