apiVersion: v1
kind: Service
metadata:
  name: blog-svc
  namespace: blog
  labels:
    app: blog
spec:
  type: ClusterIP
  ports:
    - port: 80
      name: http
  selector:
    app: blog
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: blog-ingress
  namespace: blog
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  tls:
    - hosts:
        - justinhung.space
      secretName: acme-crt-secret
  rules:
    - host: justinhung.space
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: blog-svc
                port:
                  number: 80
---
# apiVersion: networking.istio.io/v1beta1
# kind: VirtualService
# metadata:
#   name: blog-vs
#   namespace: blog
# spec:
#   gateways:
#     - istio-system/default
#     - mesh
#   hosts:
#     - blog-svc.blog.svc.cluster.local
#     - blog.127-0-0-1.nip.io
#     - blog.justihung.space
#   http:
#     - route:
#         - destination:
#             host: blog-svc.blog.svc.cluster.local
#             port:
#               number: 80
